version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - pwd && ls && whoami
      - mvn spotless:apply
      - ./mvnw clean install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  discard-paths: no
    #- target/*.jar
    #- script/start.sh
    #- appspec.yml
    #- buildspec_owasp_dependency_check.yml
    #- buildspec_sonarqube.yml
    